# Note  : *** the batch_size should be equal to the gpus number at the test phase!!! ***
data_cfg:
  dataset_name: GREW
  dataset_root: path
  dataset_partition: ./datasets/GREW/GREW.json
  num_workers: 16
  remove_no_gallery: false # Remove probe if no gallery for it
  test_dataset_name: GREW

evaluator_cfg:
  enable_float16: false 
  restore_ckpt_strict: true
  restore_hint: 240000
  save_name: GaitGL_mimic_full_guided
  eval_func: evaluate_real_scene # identification_real_scene # identification_GREW_submission
  sampler:
    batch_size: 8
    sample_type: all_ordered
    type: InferenceSampler
  transform:
    - type: Compose
      trf_cfg:
        - type: BaseSilTransform
        - type: MimicFullTransform
          occlusion_range: [0.4, 0.6]
          img_size: 64
loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLossFlat
    log_prefix: triplet
  # - loss_term_weight: 1.0
  #   scale: 1
  #   type: CrossEntropyLoss
  #   log_accuracy: true
  #   label_smooth: true
  #   log_prefix: softmax

model_cfg:
  model: GaitGL_Mimic_Full_Guided
  channels: [32, 64, 128, 256]
  class_num: 20000
  OccMixerFCs:
    in_channels: 320
    out_channels: 256
    parts_num: 64
  occ_detector_path: path
  mimic_cfg:
    phase: 2  
    teacher_model_name: GaitGL
    teacher_save_name: GaitGL_no_occ
    teacher_model_iter: 250000   #250000

optimizer_cfg:
  lr: 1.0e-4
  solver: Adam
  weight_decay: 0

scheduler_cfg:
  gamma: 0.1
  milestones:
    - 150000
    - 200000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true
  with_test: true
  log_iter: 2000
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 20000
  save_name: GaitGL_mimic_full_guided
  sync_BN: true
  total_iter: 250000
  sampler:
    batch_shuffle: true
    batch_size:
      - 32
      - 4
    frames_num_fixed: 30
    frames_skip_num: 0
    sample_type: fixed_ordered
    type: TripletSampler
  transform:
    - type: Compose
      trf_cfg:
        - type: BaseSilTransform
        - type: MimicFullTransform
          occlusion_range: [0.4, 0.6]
          img_size: 64
  
  
