data_cfg:
  dataset_name: Gait3D
  dataset_root: path
  dataset_partition: ./datasets/Gait3D/Gait3D.json
  num_workers: 5
  remove_no_gallery: false # Remove probe if no gallery for it
  test_dataset_name: Gait3D

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: 100000
  save_name: GaitGL_Gait3D_BL1
  eval_func: evaluate_Gait3D
  sampler:
    batch_shuffle: false
    batch_size: 4
    sample_type: all_ordered # all indicates whole sequence used to test, while ordered means input sequence by its natural order; Other options:   fixed_unordered
    frames_all_limit: 720 # limit the number of sampled frames to prevent out of memory
  metric: euc # cos
  transform:
    - type: Compose
      trf_cfg:
        - type: BaseSilTransform
        - type: Occlusion
          shape_cfgs: 
            - type: ConsistentHalfPatchTwoTypesResized
              prob: 1.0
              portion_range: [0.4, 0.6]

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true

model_cfg:
  model: GaitGL
  channels: [32, 64, 128, 256]
  class_num: 3000

optimizer_cfg:
  lr: 1.0e-4
  solver: Adam
  weight_decay: 0

scheduler_cfg:
  gamma: 0.1
  milestones: # Learning Rate Reduction at each milestones
    - 20000
    - 40000
    - 50000
  scheduler: MultiStepLR


trainer_cfg:
  enable_float16: true # half_percesion float for memory reduction and speedup
  fix_BN: false
  with_test: true
  log_iter: 1000
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 20000
  save_name: GaitGL_Gait3D_BL1
  sync_BN: true
  total_iter: 100000
  sampler:
    batch_shuffle: true
    batch_size:
      - 32 # TripletSampler, batch_size[0] indicates Number of Identity
      - 4 #                 batch_size[1] indicates Samples sequqnce for each Identity
    frames_num_fixed: 30 # fixed frames number for training
    sample_type: fixed_ordered # fixed control input frames number, unordered for controlling order of input tensor; Other options: unfixed_ordered or all_ordered
    frames_skip_num: 0
    type: TripletSampler
  transform:
    - type: Compose
      trf_cfg:
        - type: BaseSilTransform
        
