# Note  : *** the batch_size should be equal to the gpus number at the test phase!!! ***
data_cfg:
  dataset_name: GREW
  dataset_root: path
  dataset_partition: ./datasets/GREW/GREW.json
  num_workers: 16
  remove_no_gallery: false # Remove probe if no gallery for it
  test_dataset_name: GREW

evaluator_cfg:
  enable_float16: false 
  restore_ckpt_strict: true
  restore_hint: 250000
  save_name: GaitGL_no_occ
  eval_func: evaluate_real_scene # identification_real_scene # identification_GREW_submission
  sampler:
    batch_size: 4
    sample_type: all_ordered
    type: InferenceSampler
  transform:
    - type: Compose
      # trf_cfg:
      #   - type: BaseSilCuttingTransform
      #   - type: Occlusion
      #     shape_cfgs:
      #       - type: MovingPatch
      #         prob: 0.5
      #         width_range: [0.3, 0.5]
      #         height_range: [0.3, 0.5]
      #         velocity_range: [0.5, 1.0]  #number of pixels moved per frame
      #       - type: MovingPole
      #         prob: 0.5
      #         width_range: [0.2, 0.4]
      #         velocity_range: [0.5, 1.0]  #number of pixels moved per frame
      trf_cfg:
        - type: BaseSilTransform
        - type: Occlusion
          shape_cfgs: 
            - type: ConsistentHalfPatchTwoTypesResized
              prob: 1.0
              portion_range: [0.4, 0.6]

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 1
    type: CrossEntropyLoss
    log_accuracy: true
    label_smooth: true
    log_prefix: softmax

model_cfg:
  model: GaitGL
  channels: [32, 64, 128, 256]
  class_num: 20000

optimizer_cfg:
  lr: 1.0e-4
  solver: Adam
  weight_decay: 0

scheduler_cfg:
  gamma: 0.1
  milestones:
    - 150000
    - 200000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true
  with_test: true
  log_iter: 1000
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 10000
  save_name: GaitGL_no_occ
  sync_BN: true
  total_iter: 250000
  sampler:
    batch_shuffle: true
    batch_size:
      - 32
      - 4
    frames_num_fixed: 30
    frames_skip_num: 0
    sample_type: fixed_ordered
    type: TripletSampler
  transform:
    - type: BaseSilCuttingTransform
